### ISSUE TITLE
getters and setters, does not show up in json

### ISSUE THREAD

**Issue by aryeharmon** [DScheglov/mongoose-schema-jsonschema#5]
```
var BookSchema = new Schema({
    title: {type: String, required: true},
    year: Number,
    author: {type: String, required: true, get: function() { return 123; }}
});
```

returns:
```
{ type: 'object',
  properties: 
   { title: { type: 'string' },
     year: { type: 'number' },
     author: { type: 'string' },
     _id: { type: 'string', pattern: '^[0-9a-fA-F]{24}$' } },
  required: [ 'title', 'author' ] }
```

as you can see the object does not include the get function.

**Comment by DScheglov** [comment]
Hi, please, add sample as you think the get function should be on the json schena

**Comment by aryeharmon** [comment]
Probably in string format. so we can turn in back into a mongoose model with `exec()`

{ type: 'object',
  properties: 
   { title: { type: 'string' },
     year: { type: 'number' },
     author: { type: 'string', get: 'function() { return 123; }' },
     _id: { type: 'string', pattern: '^[0-9a-fA-F]{24}$' } },
  required: [ 'title', 'author' ] }

**Comment by aryeharmon** [comment]
also, I notice required is missing as well.

**Comment by DScheglov** [comment]
The getters also as setters are not allowed by the json-schema: http://json-schema.org/. Because  it is a behavior of the data but not a structure and constraints. The Functions and Dates are not valid JSON types.

So, I'm closing the issue as not applicable to json-schema.
You always can fork the repository and write any code you need. Good luck
